### ISSUE TITLE
Improvements to Saber m4 code. 

### ISSUE THREAD

**Issue by mvanbeirendonck** [ntt-polymul/ntt-polymul#2]
Hi all,

First of all, apologies for the long message, and thank you for bringing the NTT Multiplication to NTT-unfriendly rings! 

I spent some time optimizing the NTT-based Saber Cortex-m4 implementation, as well as merging improvements from other repositories. I grouped all of this in a large commit (not the best practice, my apologies) at https://github.com/mvanbeirendonck/pqm4. 

The info on the changes I made to the NTT-based multiplication are in the second part of the commit message (f390aea), but I wanted to detail these a little more here. Any feedback is welcome, because I might have overlooked things. Benchmarks are included in the repository. You'll find that this new implementation is slightly faster (~2.5%/~5%/~8%) for (keygen/encaps/decaps), but especially uses significantly less memory (~30%/~60%/~60%). Feel free to use these numbers for memory consumption if you want to report them somewhere.

- If I understand correctly, the only difference between `NTT_forward` and `NTT_forward_pk` is the central-reduction in the `_pk` variant. However, to the best of my knowledge, Saber doesn't need these reductions. Saber can perfectly handle signed `int16_t` everywhere.
    - For example, in indcpa_kem_dec (lines 262-266), the secret key is reduced `mod_p`. Then, in `NTT_forward_pk`, it is again central-reduced. These two operations exactly cancel each other out. It seems possible to remove `NTT_forward_pk` and reuse `NTT_forward` and `int16_t` everywhere, which I did in my implementation. Central-reduction is now integrated into the unpacking operations.
    - It also seems your implementation might still have a potential overflow. The matrix A is not central-reduced but is still used with `NTT_forward`. In `GenMatrix`, I believe you uncommented the modular reduction, but the exact same reduction is still present in `BS2POL`.
- For the same reasons, the central-reduction and `mod_p` or `mod_q` at the end of `NTT_inv` seems unnecessary and can be removed.
- During encryption, `NTT_forward(s')` is computed twice. Once in `MatrixVectorMul` and once in `InnerProd`. I pulled this out of these functions so that it only needs to be computed once.
- I also spent some time improving the memory footprint of the NTT-based multiplication, using techniques of [ia.cr/2018/682, Section 2.2]. The basic idea is to generate NTT elements on-the-fly and maximally reuse buffers. With the incremental SHAKE-128 this is relatively easy to implement. 

At the moment, this last bullet point is implemented on the level of polynomial vectors. For a truly memory-efficient variant, it would be interesting to extend this to individual polynomials. For this, it would be necessary to decompose the `my_mul` schoolbook accumulation, such that you can input polynomials instead of vectors of polynomials. I wanted to ask if you by any chance have such a function from previous tests, maybe before you created the efficient assembly? You can have a look at the function `MatrixVectorMulKeyPairJIT` for an idea of what this would need to look like. 

Performance would suffer a bit from decomposing `my_mul`, but stack usage could greatly improve. As a rough estimate for Saber, we would need to store 10 fewer NTT polynomials during KeyPair generation and 4 fewer NTT polynomials during Encaps and Decaps.

KeyPair: 17,028 -> 6,788 (bytes)
Encaps: 12,684 -> 8,588 (bytes)
Decaps: 12,700 -> 8,604 (bytes)

This brings the NTT-based multiplication extremely close to other multiplication methods for Saber in terms of memory consumption.

Thanks for any help!

Michiel

**Comment by mkannwischer** [comment]
Thanks, Michiel! 
That was indeed something that was still on our list to do, but we didn't get around to do it so far. Nice to see that it actually works out as expected! I'll get it merged here and in pqm4. 

I'm sure we can find a mul that only takes polynomials somewhere. I'll get back to you.

**Comment by mvanbeirendonck** [comment]
Happy to help! I figured that indeed you must have thought of implementing these memory optimisations. I'm glad they were still on the to-do list, and they don't overlap with your work. 

As soon as I get the memory-efficient variant working, I'll submit the relevant pull requests. It will maybe depend a little on how much this hurts efficiency to see which version is more appropriate for pqm4.

**Comment by mkannwischer** [comment]
If there is a huge performance gap, I would probably go for having two implementations in pqm4.

**Comment by vincentvbh** [comment]
Hi, Michiel.
Thanks a lot for integrating several optimizations into the code. 
I think there is a problem with NTT_inv and NTT_inv_inner. The central_reduce in NTT_forward and the central_reduce in NTT_inv are not the same things and the 'and' is required(we can change this to sbfx for int16_t).

The central_reduce in NTT_forward(for matrix A) map elements to [-(SABER_Q / 2), (SABER_Q / 2) ) as required for the signed NTT. As long as the input is put into [-(SABER_Q / 2), (SABER_Q / 2) ), we don't need the central_reduce. Additionally, you are right that there is still a potential overflow because we forget to modify BS2POL. 

The central_reduce in NTT_inv and NTT_inv_inner is another thing and it is part of the design of NTT-based multiplication. Recall that at the end of the NTT trick, we must multiply each coefficient by (64^{-1} mod M)^\pm where M is the MOD in NTT.h. We multiply each coefficient by (64^{-1} R^2 mod M)^\pm (where R = 2^32) with Montgomery multiplication(an additional R is required because the my_mul function computes the result in Montgomery domain). For the signed NTT trick, we want to assemble the signed result in Z and then reduce them to [-(SABER_Q / 2), (SABER_Q / 2) ) for int16_t, so the NTT trick should compute the result in [-(M / 2), (M / 2) ). Unfortunately, the result of Montgomery multiplication is in (-M, M). The central_reduce in NTT_inv and NTT_inv_inner is to reduce elements in (-M, M) to [-(M / 2), (M / 2) ). We can't apply Barrett reduction because M is too big.

Finally, the 'and' at the end of NTT_inv and NTT_inv_inner is also required. After Montgomery_multiplying (64^{-1} mod M)^\pm, the result is in (-M, M), and we need them in [-(SABER_Q / 2), (SABER_Q / 2) ). Originally, we 'and' to have them in [0, SABER_Q) for uint16_t, now we can 'sbfx' to have them in [-(SABER_Q / 2), (SABER_Q / 2) ).

For the my_mul function taking only one polynomial, is not hard to produce one. However, there will be some overflow problem in NTT_inv and NTT_inv_inner if we do so. I'll soon produce a my_mul with only one polynomial and NTT_inv and NTT_inv_inner preventing such potential overflow.

Vincent

**Comment by mvanbeirendonck** [comment]
Hi Matthias, Vincent,

It's still a little work-in-progress, but with Vincent's decomposed multiplication I managed to get the 'memory-efficient' NTT running! At the moment, in https://github.com/mvanbeirendonck/pqm4, you can select between 'fast' and 'memory-efficient' with the macro `SABER_MEMORY_EFFICIENT`.

I included benchmark results for ['fast'](https://github.com/mvanbeirendonck/pqm4/blob/master/benchmarks-fast.md) and ['memory-efficient'](https://github.com/mvanbeirendonck/pqm4/blob/master/benchmarks-mem-efficient.md). The performance gap turned out to be quite negligible. For Saber, you pay (2.3% / 1.9% / 2.5%) extra cycles to reduce memory by a further (60.2% / 40.4% / 40.4%). I would say it makes sense only to have this memory-efficient (but still very fast) implementation in pqm4? 

Thanks a lot for your prompt help! I'll wrap up the implementation and submit pull requests, but this might be after the holidays only. 

One more question @mkannwischer. This new implementation also has the option to compress the secret key. Because the same is not implemented in PQClean, this causes pqm4's `testvectors.c` to fail when the secret keys are checked against each other. Is there a preferred way to handle something like this? Or should I just implement the same functionality in PQClean? This could also allow a variant where the secret key is stored in NTT-format, which I believe you already do in the AVX implementation?

Best,
Michiel

**Comment by mkannwischer** [comment]
Hello @mvanbeirendonck, 

Thank you for all the work!

Unfortunately, pqm4 requires implementations to have the same secret key format to be compatible. You cannot fix it in PQClean either because those implementations should be compatible with the reference implementations submitted to NIST. The preferred way for pqm4 is not to do it. That is a bit annoying in this case.

**Comment by vincentvbh** [comment]
Hi, all,

I have refactored Saber's stack optimized NTT code to improve the readability. Furthermore, I extracted the macros for radix-2 NTTs and added a bunch of comments so that there are generic in the sense that we can treat them as building blocks for NTTs in Saber, NTRU, and NTRU Prime.

Now I think we could just have the stack optimized one since the gap between the stack optimized one and the fast one is kind of neglectable. How do you think? Another reason for just keeping the stack optimized is that I'm lazy to work on the fast one.

By the way, I cloned the commit 61da84b3674c0f7284f590b4c70299085ec0b250 in Michiel's repository and tested the changes locally. How should we proceed with the code?

Cheers, 
Vincent

**Comment by mvanbeirendonck** [comment]
Hi Vincent,

Getting the stack-optimized NTT ready to be merged here and in pqm4 has been on my TODO list for some time now, my apologies. 

I still have a commit ready locally on top of 61da84b that removes the compressing of the secret key. This makes the implementation again compatible with pqm4, as Matthias suggested. Like you, I also decided that the fast implementation wasn't worth it, and moved everything inside `#ifndef SABER_MEMORY_EFFICIENT` to separate 'fast' functions, which are currently not used.

I could push this local work by the end of today. Do you prefer to merge your refactoring and readability changes into mine, or the other way around? After that, for me the code is ready to be merged here and in pqm4!

Cheers,
Michiel

**Comment by vincentvbh** [comment]
Hi Michiel,

I think merging into your repository is good.

Cheers,
Vincent

**Comment by vincentvbh** [comment]
Hi Michiel,

I have initiated a pull request in your repository.

Vincent

**Comment by mvanbeirendonck** [comment]
Thanks, Vincent! I merged your pull request, and submitted my own pull requests to the upstream repositories. The pull request here (#3) has some questions for you.

I think we could close this issue request now and go from the pull requests? 

Thanks for all the help,
Michiel
